# Generated by Django 4.2.16 on 2024-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='deal_bas_r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ttb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.FloatField(),
        ),
    ]
